version: '3.8'
services:
  app:
    build: .
    ports:
      - "8501:8501" # Streamlit runs on port 8501 by default
    volumes:
      - .:/app
    command: streamlit run main.py
    environment:
      - STREAMLIT_SERVER_PORT=8501